//! Zebra/Zakura gRPC indexer client
//!
//! ChainTipChange remains the canonical wake-up signal. The optional
//! NonFinalizedStateChange stream supplies encoded block bytes so live indexing
//! can avoid per-transaction JSON-RPC calls.

pub mod proto {
    // This code is generated by tonic. Rust 1.98 started flagging tonic::Status
    // return values as large errors, which cannot be changed at this boundary.
    #![allow(clippy::result_large_err)]
    tonic::include_proto!("zebra.indexer.rpc");
}

use proto::indexer_client::IndexerClient;
use proto::Empty;
use std::collections::{HashMap, VecDeque};
use std::sync::Arc;
use std::time::{Duration, Instant};
use tokio::sync::{Mutex, Notify};
use tonic::transport::{Channel, Endpoint};
use tonic::Streaming;
use zakura_chain::block::Header;
use zakura_chain::serialization::ZcashDeserialize;

async fn connect_channel(url: &str) -> Result<Channel, String> {
    Endpoint::from_shared(url.to_string())
        .map_err(|e| format!("Invalid gRPC URL: {e}"))?
        .connect_timeout(Duration::from_secs(10))
        .tcp_keepalive(Some(Duration::from_secs(30)))
        .connect()
        .await
        .map_err(|e| format!("gRPC connect failed: {e}"))
}

/// Connect to Zebra's gRPC indexer and return a ChainTipChange stream.
/// The stream yields `BlockHashAndHeight` messages whenever a new block is added.
pub async fn connect_chain_tip_stream(
    url: &str,
) -> Result<Streaming<proto::BlockHashAndHeight>, String> {
    let mut client = IndexerClient::new(connect_channel(url).await?);

    let stream = client
        .chain_tip_change(Empty {})
        .await
        .map_err(|e| format!("ChainTipChange subscribe failed: {e}"))?
        .into_inner();

    Ok(stream)
}

/// Connect to the encoded non-finalized block stream.
pub async fn connect_block_stream(url: &str) -> Result<Streaming<proto::BlockAndHash>, String> {
    let fork_tips = super::ZebraRpc::from_env()?.get_fork_tip_hashes().await?;
    connect_block_stream_after_forks(url, fork_tips).await
}

/// Subscribe after known valid forks plus a fresh canonical tip. RPC catch-up
/// remains authoritative; the block stream is only a bounded live payload cache.
pub async fn connect_block_stream_after_forks(
    url: &str,
    mut fork_tips: Vec<Vec<u8>>,
) -> Result<Streaming<proto::BlockAndHash>, String> {
    if fork_tips.len() >= zakura_chain::parameters::MAX_NON_FINALIZED_CHAIN_FORKS
        || fork_tips.iter().any(|hash| hash.len() != 32)
    {
        return Err("Invalid block stream fork tips".to_string());
    }
    let mut client = IndexerClient::new(connect_channel(url).await?);
    // Empty subscriptions replay the entire non-finalized window, which can
    // fill Zakura's listener buffer before it starts draining. Begin after a
    // fresh canonical tip on every reconnect. Live indexing catches any gap
    // through RPC, so this bounded cache need not replay historical blocks.
    let mut tips = client
        .chain_tip_change(Empty {})
        .await
        .map_err(|e| format!("Block stream tip subscribe failed: {e}"))?
        .into_inner();
    let tip = tokio::time::timeout(Duration::from_secs(15), tips.message())
        .await
        .map_err(|_| "Block stream tip snapshot timed out".to_string())?
        .map_err(|e| format!("Block stream tip snapshot failed: {e}"))?
        .ok_or_else(|| "Block stream tip snapshot ended".to_string())?;
    if tip.hash.len() != 32 {
        return Err(format!(
            "Block stream tip hash has {} bytes",
            tip.hash.len()
        ));
    }
    if !fork_tips.contains(&tip.hash) {
        fork_tips.push(tip.hash);
    }
    client
        .non_finalized_state_change(proto::NonFinalizedStateChangeRequest {
            chain_tip_hashes: fork_tips,
            receipt_session: None,
        })
        .await
        .map(|response| response.into_inner())
        .map_err(|e| format!("NonFinalizedStateChange subscribe failed: {e}"))
}

#[derive(Clone)]
pub struct EncodedBlock {
    pub hash: String,
    pub data: Arc<[u8]>,
    pub received_at: Instant,
}

#[derive(Clone)]
pub struct BlockPayloadCache {
    inner: Arc<Mutex<PayloadCacheInner>>,
    notify: Arc<Notify>,
}

struct PayloadCacheInner {
    entries: HashMap<String, EncodedBlock>,
    order: VecDeque<String>,
    bytes: usize,
    max_blocks: usize,
    max_bytes: usize,
}

impl BlockPayloadCache {
    pub fn new(max_blocks: usize, max_bytes: usize) -> Result<Self, String> {
        if max_blocks == 0 || max_bytes == 0 {
            return Err("gRPC payload cache limits must be non-zero".to_string());
        }
        Ok(Self {
            inner: Arc::new(Mutex::new(PayloadCacheInner {
                entries: HashMap::with_capacity(max_blocks),
                order: VecDeque::with_capacity(max_blocks),
                bytes: 0,
                max_blocks,
                max_bytes,
            })),
            notify: Arc::new(Notify::new()),
        })
    }

    async fn insert(&self, block: EncodedBlock) {
        let mut cache = self.inner.lock().await;
        if cache.entries.contains_key(&block.hash) {
            return;
        }
        if block.data.len() > cache.max_bytes {
            tracing::warn!(
                block_bytes = block.data.len(),
                cache_max_bytes = cache.max_bytes,
                "dropping block larger than gRPC payload cache"
            );
            return;
        }

        while cache.entries.len() >= cache.max_blocks
            || cache.bytes.saturating_add(block.data.len()) > cache.max_bytes
        {
            let Some(oldest_hash) = cache.order.pop_front() else {
                break;
            };
            if let Some(oldest) = cache.entries.remove(&oldest_hash) {
                cache.bytes = cache.bytes.saturating_sub(oldest.data.len());
            }
        }

        cache.bytes = cache.bytes.saturating_add(block.data.len());
        cache.order.push_back(block.hash.clone());
        cache.entries.insert(block.hash.clone(), block);
        drop(cache);
        self.notify.notify_waiters();
    }

    pub async fn take(&self, hash: &str) -> Option<EncodedBlock> {
        let mut cache = self.inner.lock().await;
        let block = cache.entries.remove(hash)?;
        cache.bytes = cache.bytes.saturating_sub(block.data.len());
        cache.order.retain(|cached_hash| cached_hash != hash);
        Some(block)
    }

    pub async fn take_wait(&self, hash: &str, timeout: Duration) -> Option<EncodedBlock> {
        let deadline = tokio::time::Instant::now() + timeout;
        loop {
            // Register before checking the cache so an insertion between the
            // check and await cannot be missed.
            let notified = self.notify.notified();
            if let Some(block) = self.take(hash).await {
                return Some(block);
            }
            let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
            if remaining.is_zero() || tokio::time::timeout(remaining, notified).await.is_err() {
                return None;
            }
        }
    }
}

fn validate_payload(message: proto::BlockAndHash) -> Result<EncodedBlock, String> {
    if message.hash.len() != 32 {
        return Err(format!(
            "NonFinalizedStateChange returned a {}-byte hash",
            message.hash.len()
        ));
    }
    if message.data.is_empty() {
        return Err("NonFinalizedStateChange returned an empty block".to_string());
    }

    let header = Header::zcash_deserialize(&mut std::io::Cursor::new(&message.data))
        .map_err(|e| format!("invalid encoded block header: {e:?}"))?;
    let advertised_hash = hex::encode(message.hash);
    let decoded_hash = header.hash().to_string();
    if advertised_hash != decoded_hash {
        return Err(format!(
            "gRPC block hash mismatch: advertised {advertised_hash}, decoded {decoded_hash}"
        ));
    }

    Ok(EncodedBlock {
        hash: advertised_hash,
        data: Arc::from(message.data),
        received_at: Instant::now(),
    })
}

/// Keep the full-block stream connected and cache only hash-validated payloads.
/// A stream failure never stops live indexing because RPC remains authoritative.
pub async fn supervise_block_stream(url: String, cache: BlockPayloadCache) {
    let mut retry_delay = Duration::from_secs(1);
    loop {
        match connect_block_stream(&url).await {
            Ok(mut stream) => {
                tracing::info!("NonFinalizedStateChange stream connected");
                retry_delay = Duration::from_secs(1);
                loop {
                    match stream.message().await {
                        Ok(Some(message)) => match validate_payload(message) {
                            Ok(block) => cache.insert(block).await,
                            Err(error) => tracing::warn!(%error, "rejected gRPC block payload"),
                        },
                        Ok(None) => {
                            tracing::warn!("NonFinalizedStateChange stream ended");
                            break;
                        }
                        Err(error) => {
                            tracing::warn!(%error, "NonFinalizedStateChange stream failed");
                            break;
                        }
                    }
                }
            }
            Err(error) => {
                tracing::warn!(%error, "failed to connect full-block gRPC stream");
            }
        }

        tokio::time::sleep(retry_delay).await;
        retry_delay = retry_delay.saturating_mul(2).min(Duration::from_secs(30));
    }
}

#[cfg(test)]
mod tests {
    use super::{BlockPayloadCache, EncodedBlock};
    use std::sync::Arc;
    use std::time::Instant;

    fn block(hash: &str, size: usize) -> EncodedBlock {
        EncodedBlock {
            hash: hash.to_string(),
            data: Arc::from(vec![0; size]),
            received_at: Instant::now(),
        }
    }

    #[tokio::test]
    async fn payload_cache_enforces_count_limit() {
        let cache = BlockPayloadCache::new(2, 100).expect("valid cache");
        cache.insert(block("a", 10)).await;
        cache.insert(block("b", 10)).await;
        cache.insert(block("c", 10)).await;

        assert!(cache.take("a").await.is_none());
        assert!(cache.take("b").await.is_some());
        assert!(cache.take("c").await.is_some());
    }

    #[tokio::test]
    async fn payload_cache_enforces_byte_limit() {
        let cache = BlockPayloadCache::new(10, 15).expect("valid cache");
        cache.insert(block("a", 10)).await;
        cache.insert(block("b", 10)).await;

        assert!(cache.take("a").await.is_none());
        assert!(cache.take("b").await.is_some());
    }
}
